expression = atom | list
list = <leftdelimiter> <spc*> operator operands <spc*> <rightdelimiter>
operator = identifier | list
operands = (<spc+> (atom | list))*
atom = number | identifier
number = #"[0-9]+"
identifier = keyword | #"[a-za-z\-\+][a-za-z\-\+\*\/0-9]*"
leftdelimiter = "("
rightdelimiter = ")"
spc = #"\s"
keyword = "fn" | "def"
