expression =  <leftdelimiter> <whitespace*> operator operands <whitespace*> <rightdelimiter>
operator = expression | keyword | !keyword identifier
operands = (<whitespace+> (expression | identifier | number))+
identifier = #"[a-z][a-z]*[0-9]*"
keyword = "define"
number = #"[0-9]+"
whitespace = #"\s"
leftdelimiter = "("
rightdelimiter = ")"
