expression = atom | list
list = <leftdelimiter> <spc*> operator operands <spc*> <rightdelimiter>
operator = identifier | list
operands = ((<spc+> atom)* | (<spc*> list)*)*
atom = (identifier | number | string)
identifier = keyword / #"[a-zA-Z\-\+\/*\//][a-za-z\-\+\*\/0-9]*"
number = #"[0-9]+"
string = (#"\"[a-zA-Z\s]*\"")+
keyword = "fun" | "define" | "list"
rightdelimiter = ")"
leftdelimiter = "("
spc = #"\s"